### ISSUE TITLE
Solace Source connector for kafka crashing

### ISSUE THREAD

**Issue by lakshmanpython** [SolaceProducts/pubsubplus-connector-kafka-source#10]
Hi Solace Team,

Kindly help to provide solution. After messages pilledup at solace. Kafka connector is crashing frequently.. Please find below exceptions.

169887 [2019-07-22 14:14:35,386] ERROR WorkerSourceTask{id=source.solace.apac.hk.custmgt.ecl.ecl.raw.int.eclipselog-2} Task threw an uncaught and unrecoverable exception (org.ap ache.kafka.connect.runtime.WorkerTask)
169888 java.lang.NullPointerException
169889 at com.solace.source.connector.msgprocessors.SolaceEHKeyMessageProcessor.process(SolaceEHKeyMessageProcessor.java:70)
169890 at com.solace.source.connector.SolaceSourceTask.poll(SolaceSourceTask.java:166)
169891 at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
169892 at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
169893 at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
169894 at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
169895 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
169896 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
169897 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
169898 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
169899 at java.lang.Thread.run(Thread.java:748)
169900 [2019-07-22 14:14:35,387] ERROR WorkerSourceTask{id=source.solace.apac.hk.asdadadadsad.raw.int.log-2} Task is being killed and will not recover until manually r estarted (org.apache.kafka.connect.runtime.WorkerTask) 
{
"connector": {
"state": "RUNNING",
"worker_id": "host_connector:8072"
},
"name": "source.solace.apac.hk.custmgt.ecl.ecl.raw.int.eclipselog",
"tasks": [
{
"id": 0,
"state": "FAILED",
"trace": "java.lang.NullPointerException\n\tat com.solace.source.connector.msgprocessors.SolaceEHKeyMessageProcessor.process(SolaceEHKeyMessageProcessor.java:70)\n\tat com.solace.source.connector.SolaceSourceTask.poll(SolaceSourceTask.java:166)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n",
"worker_id": "host_connector:8072"
},
{
"id": 1,
"state": "FAILED",
"trace": "java.lang.NullPointerException\n\tat com.solace.source.connector.msgprocessors.SolaceEHKeyMessageProcessor.process(SolaceEHKeyMessageProcessor.java:70)\n\tat com.solace.source.connector.SolaceSourceTask.poll(SolaceSourceTask.java:166)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n",
"worker_id": "host_connector:8072"

Regards
Lakshman

**Comment by bczoma** [comment]
There is work underway to update the connectors, which will include addressing this issue
