### ISSUE TITLE
when connector and kafka both down, solace messages may be losted

### ISSUE THREAD

**Issue by leadingsoftjp** [SolaceProducts/pubsubplus-connector-kafka-source#14]
1. solace publish message.
2. shutdown kafka broker.
3. shutdown connector.
4. restart kafka broker.
5. restart connector.

The message of 1 does not be transfered to kafka topic, but it has already consumed from solace queue.  I found in the poll method it manually call the commit method by self, should let kafka connector call it automatically?

https://github.com/SolaceLabs/pubsubplus-connector-kafka-source/blob/master/src/main/java/com/solace/source/connector/SolaceSourceTask.java#L179-L182

**Comment by aaitsalem** [comment]
Hello, 
I have the same problem with.
when this fix can pass ?

**Comment by bczoma** [comment]
There is work underway to update the connectors, which will include addressing this issue - ETA is April.
